# -*- coding: utf-8 -*-
"""ML_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7liRAj_C9HS9InM9mmItaV3ueeScpNX
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("location_aware_gis_leakage_dataset.csv")
df.head()



import pandas as pd
import numpy as np

df.shape

df.info()

import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv("location_aware_gis_leakage_dataset.csv")

# 1. Add a timestamp column (random dates within a range)
start_date = pd.to_datetime("2023-01-01")
end_date = pd.to_datetime("2023-12-31")
df['timestamp'] = pd.to_datetime(np.random.randint(start_date.value//10**9,
                                                  end_date.value//10**9,
                                                  size=len(df)), unit='s')

# 2. Add a leak number column (could be sequential or random)
df['leak_no'] = np.random.randint(1, 101, size=len(df))  # leak numbers 1 to 100

# Check the first few rows
print(df.head())

df.head()

print(df.columns.tolist())

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("location_aware_gis_leakage_dataset.csv")

# Step 1: Add timestamp column (random dates in 2023)
start_date = pd.to_datetime("2023-01-01")
end_date = pd.to_datetime("2023-12-31")
df['timestamp'] = pd.to_datetime(
    np.random.randint(start_date.value//10**9, end_date.value//10**9, size=len(df)), unit='s'
)

# Step 2: Add leak_no column (random integers 1-100)
df['leak_no'] = np.random.randint(1, 101, size=len(df))

# Step 3: Define numeric columns for outliers
numeric_cols = ['Pressure', 'Flow_Rate', 'Temperature', 'Vibration', 'RPM', 'Operational_Hours']

# Step 4: Add outliers in 4th and 5th row (indices 3 and 4)
df.loc[3, numeric_cols] = df.loc[3, numeric_cols] * 5   # row 4 outlier
df.loc[4, numeric_cols] = df.loc[4, numeric_cols] * 10  # row 5 extreme outlier

# Step 5: Add outliers in leak_no
df.loc[3, 'leak_no'] = df['leak_no'].max() + 200
df.loc[4, 'leak_no'] = df['leak_no'].max() + 500

# Step 6 (optional): Add timestamp outliers
df.loc[3, 'timestamp'] = pd.to_datetime("2010-01-01")  # far past
df.loc[4, 'timestamp'] = pd.to_datetime("2035-01-01")  # far future

# Check the modified rows
print(df.iloc[3:5])

df.tail()

import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv("location_aware_gis_leakage_dataset.csv")

# Ensure 'timestamp' and 'leak_no' exist; if not, create them
if 'timestamp' not in df.columns:
    start_date = pd.to_datetime("2023-01-01")
    end_date = pd.to_datetime("2023-12-31")
    df['timestamp'] = pd.to_datetime(
        np.random.randint(start_date.value//10**9, end_date.value//10**9, size=len(df)), unit='s'
    )

if 'leak_no' not in df.columns:
    df['leak_no'] = np.random.randint(1, 101, size=len(df))

# Define numeric columns to add outliers
numeric_cols = ['Pressure', 'Flow_Rate', 'Temperature', 'Vibration', 'RPM', 'Operational_Hours']

# Add outliers to first two rows
df.loc[0, numeric_cols] = df.loc[0, numeric_cols] * 5    # Row 1 extreme values
df.loc[1, numeric_cols] = df.loc[1, numeric_cols] * 10   # Row 2 even more extreme

# Add outliers in leak_no
df.loc[0, 'leak_no'] = df['leak_no'].max() + 300
df.loc[1, 'leak_no'] = df['leak_no'].max() + 500

# Optional: add timestamp outliers
df.loc[0, 'timestamp'] = pd.to_datetime("2010-01-01")  # far past
df.loc[1, 'timestamp'] = pd.to_datetime("2035-01-01")  # far future

# Check first two rows
print(df.iloc[0:2])

print(df.describe())

import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv("location_aware_gis_leakage_dataset.csv")

# Ensure timestamp and leak_no exist
if 'timestamp' not in df.columns:
    start_date = pd.to_datetime("2023-01-01")
    end_date = pd.to_datetime("2023-12-31")
    df['timestamp'] = pd.to_datetime(
        np.random.randint(start_date.value//10**9, end_date.value//10**9, size=len(df)), unit='s'
    )

if 'leak_no' not in df.columns:
    df['leak_no'] = np.random.randint(1, 101, size=len(df))

# Columns to add missing values
numeric_cols = ['Pressure', 'Flow_Rate', 'Temperature', 'Vibration', 'RPM', 'Operational_Hours', 'leak_no']
cat_cols = ['Zone', 'Block', 'Pipe', 'Location_Code', 'timestamp']

np.random.seed(42)

# Add missing values in numeric columns (e.g., 1% of rows)
num_missing = int(0.01 * len(df))
for _ in range(num_missing):
    idx = np.random.randint(0, len(df))
    col = np.random.choice(numeric_cols)
    df.loc[idx, col] = np.nan

# Add missing values in categorical/timestamp columns (e.g., 1% of rows)
for _ in range(num_missing):
    idx = np.random.randint(0, len(df))
    col = np.random.choice(cat_cols)
    df.loc[idx, col] = np.nan

# Check some rows with missing values
print(df[df.isna().any(axis=1)].head())

"""Missing values"""

df.isna().sum()

numeric_cols = ['Pressure', 'Flow_Rate', 'Temperature', 'Vibration', 'RPM', 'Operational_Hours', 'leak_no']

for col in numeric_cols:
    if col in df.columns:
        df[col].fillna(df[col].mean(), inplace=True)

cat_cols = ['Zone', 'Block', 'Pipe', 'Location_Code', 'timestamp']

for col in cat_cols:
    if col in df.columns:
        df[col].fillna(df[col].mode()[0], inplace=True)

print(df.isna().sum())

"""Outliers"""

from scipy import stats
import numpy as np


z_scores = np.abs(stats.zscore(df[numeric_cols]))
outlier_rows = (z_scores > 3).any(axis=1)
print(f"Number of outlier rows: {outlier_rows.sum()}")
print("Indices of outlier rows:", df[outlier_rows].index.tolist())


print(df[outlier_rows])

"""duplicates"""

df = df.drop_duplicates(subset=['Pressure', 'Flow_Rate'])
df = df.reset_index(drop=True)

"""categorical to numerical"""

categorical_cols = ['Zone', 'Block', 'Pipe', 'Location_Code']

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print(df_encoded.head())

"""feature selection"""

print(df_encoded[['Leakage_Flag', 'leak_no']].corr())

df_encoded = df_encoded.drop(columns=['timestamp', 'leak_no'])

print(df_encoded.columns)

"""stratified split"""

from sklearn.model_selection import train_test_split
X = df_encoded.drop(columns=['Leakage_Flag'])
y = df_encoded['Leakage_Flag']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train set:\n", y_train.value_counts(normalize=True))
print("Test set:\n", y_test.value_counts(normalize=True))

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(df.columns)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in ["Zone","Block","Pipe","Location_Code"]:
    df[col] = le.fit_transform(df[col])

"""logistic regression"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *

# Split dataset
X = df.drop(["Leakage_Flag","timestamp","leak_no"], axis=1)
y = df["Leakage_Flag"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Train Logistic Regression
model = LogisticRegression(class_weight='balanced', max_iter=5000)
model.fit(X_train, y_train)

# Predictions
y_pred_lr = model.predict(X_test)
print("Accuracy :", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr,pos_label=1))
print("Recall   :", recall_score(y_test, y_pred_lr,pos_label=1))
print("F1 Score :", f1_score(y_test, y_pred_lr,pos_label=1))

report = classification_report(y_test, y_pred, output_dict=True)
precision_lr = report['1']['precision']
recall_lr    = report['1']['recall']
f1_lr        = report['1']['f1-score']

"""Decision tree"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import *

# Define features and target
X = df.drop(["Leakage_Flag","timestamp","leak_no"], axis=1)
y = df["Leakage_Flag"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Train Decision Tree
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Predict
y_pred_dt = model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt,pos_label=1))
print("Recall   :", recall_score(y_test, y_pred_dt,pos_label=1))
print("F1 Score :", f1_score(y_test, y_pred_dt,pos_label=1))

# Extract Precision for Leak class (1)
report = classification_report(y_test, y_pred_dt, output_dict=True)
precision_dt = report['1']['precision']
recall_dt    = report['1']['recall']
f1_dt       = report['1']['f1-score']

# ===== Train vs Test Comparison =====

train_pred_dt = model.predict(X_train)
test_pred_dt = model.predict(X_test)

print("\nDecision Tree Overfitting Check:")
print("Train Accuracy:", accuracy_score(y_train, train_pred_dt))
print("Test Accuracy :", accuracy_score(y_test, test_pred_dt))

"""SVM"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import *
le = LabelEncoder()
for col in ["Zone","Block","Pipe","Location_Code"]:
    df[col] = le.fit_transform(df[col])


X = df.drop(["Leakage_Flag","timestamp","leak_no"], axis=1)
y = df["Leakage_Flag"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


model = SVC(kernel="rbf", class_weight="balanced", random_state=42)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred,pos_label=1))
print("Recall   :", recall_score(y_test, y_pred,pos_label=1))
print("F1 Score :", f1_score(y_test, y_pred,pos_label=1))

# Extract Precision for Leak class (1)
report = classification_report(y_test, y_pred, output_dict=True)
precision_svm = report['1']['precision']
recall_svm    = report['1']['recall']
f1_svm        = report['1']['f1-score']

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import *
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
le = LabelEncoder()
for col in ["Zone","Block","Pipe","Location_Code"]:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])


X = df.drop(["Leakage_Flag","timestamp","leak_no"], axis=1)
y = df["Leakage_Flag"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

results = []
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model_lr = LogisticRegression(class_weight='balanced', max_iter=5000, random_state=42)
model_lr.fit(X_train_scaled, y_train)
y_pred_lr = model_lr.predict(X_test_scaled)
report_lr = classification_report(y_test, y_pred_lr, output_dict=True)
results.append({
    'Model': 'Logistic Regression',
    'Accuracy': accuracy_score(y_test, y_pred_lr),
    'Precision (Leak)': report_lr['1']['precision'],
    'Recall (Leak)': report_lr['1']['recall'],
    'F1-Score (Leak)': report_lr['1']['f1-score']
})

model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train, y_train)
y_pred_dt = model_dt.predict(X_test)
report_dt = classification_report(y_test, y_pred_dt, output_dict=True)
results.append({
    'Model': 'Decision Tree',
    'Accuracy': accuracy_score(y_test, y_pred_dt),
    'Precision (Leak)': report_dt['1']['precision'],
    'Recall (Leak)': report_dt['1']['recall'],
    'F1-Score (Leak)': report_dt['1']['f1-score']
})

model_rf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
report_rf = classification_report(y_test, y_pred_rf, output_dict=True)
results.append({
    'Model': 'Random Forest',
    'Accuracy': accuracy_score(y_test, y_pred_rf),
    'Precision (Leak)': report_rf['1']['precision'],
    'Recall (Leak)': report_rf['1']['recall'],
    'F1-Score (Leak)': report_rf['1']['f1-score']
})


scaler_svm = StandardScaler()
X_train_scaled_svm = scaler_svm.fit_transform(X_train)
X_test_scaled_svm = scaler_svm.transform(X_test)

model_svm = SVC(kernel='rbf', class_weight='balanced', random_state=42)
model_svm.fit(X_train_scaled_svm, y_train)
y_pred_svm = model_svm.predict(X_test_scaled_svm)
report_svm = classification_report(y_test, y_pred_svm, output_dict=True)
results.append({
    'Model': 'SVM',
    'Accuracy': accuracy_score(y_test, y_pred_svm),
    'Precision (Leak)': report_svm['1']['precision'],
    'Recall (Leak)': report_svm['1']['recall'],
    'F1-Score (Leak)': report_svm['1']['f1-score']
})


results_df = pd.DataFrame(results)

display(results_df)

"""Bagging-Random Forest"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *


X = df.drop(['Leakage_Flag', 'timestamp', 'leak_no'], axis=1)
y = df['Leakage_Flag']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42,
    class_weight='balanced',
    bootstrap=True
)

# Train the model
rf_model.fit(X_train, y_train)

# Predict
y_pred = rf_model.predict(X_test)
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred,pos_label=1))
print("Recall   :", recall_score(y_test, y_pred,pos_label=1))
print("F1 Score :", f1_score(y_test, y_pred,pos_label=1))

# Extract Precision for Leak class (1)
report = classification_report(y_test, y_pred, output_dict=True)
precision_rf = report['1']['precision']
recall_rf    = report['1']['recall']
f1_rf        = report['1']['f1-score']

"""Boosting-XG BOOST"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import *
from xgboost import XGBClassifier

for col in ["Zone","Block","Pipe","Location_Code"]:
    df[col] = LabelEncoder().fit_transform(df[col])

X = df.drop(["Leakage_Flag","timestamp","leak_no"], axis=1)
y = df["Leakage_Flag"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=len(y_train[y_train==0]) / len(y_train[y_train==1]),
    random_state=42,
    use_label_encoder=False,
    eval_metric="logloss"
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred,pos_label=1))
print("Recall   :", recall_score(y_test, y_pred,pos_label=1))
print("F1 Score :", f1_score(y_test, y_pred,pos_label=1))

# Store Precision for Leak class (1)
report = classification_report(y_test, y_pred, output_dict=True)
precision_xgb = precision_score(y_test, y_pred, pos_label=1)
recall_xgb   = report['1']['recall']
f1_xgb       = report['1']['f1-score']

"""Light GBM"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import *
from lightgbm import LGBMClassifier

for col in ["Zone","Block","Pipe","Location_Code"]:
    df[col] = LabelEncoder().fit_transform(df[col])

X = df.drop(["Leakage_Flag","timestamp","leak_no"], axis=1)
y = df["Leakage_Flag"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = LGBMClassifier(
    n_estimators=100,
    learning_rate=0.1,
    class_weight="balanced",
    random_state=42,
    verbose=-1
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

report = classification_report(y_test, y_pred, output_dict=True)
precision_lgbm = precision_score(y_test, y_pred, pos_label=1)
recall_lgbm    = report['1']['recall']
f1_lgbm        = report['1']['f1-score']

"""Ada Boost"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import *
from sklearn.ensemble import AdaBoostClassifier

for col in ["Zone","Block","Pipe","Location_Code"]:
    df[col] = LabelEncoder().fit_transform(df[col])

X = df.drop(["Leakage_Flag","timestamp","leak_no"], axis=1)
y = df["Leakage_Flag"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = AdaBoostClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

report = classification_report(y_test, y_pred, output_dict=True)
precision_adaboost = precision_score(y_test, y_pred, pos_label=1)
recall_adaboost    = report['1']['recall']
f1_adaboost        = report['1']['f1-score']

train_pred_ada = model.predict(X_train)
test_pred_ada = model.predict(X_test)

print("\nAdaBoost Overfitting Check:")
print("Train Accuracy:", accuracy_score(y_train, train_pred_ada))
print("Test Accuracy :", accuracy_score(y_test, test_pred_ada))

"""Deep Learning - ANN"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import *

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

df_copy = df.copy()

for col in ["Zone","Block","Pipe","Location_Code"]:
    df_copy[col] = LabelEncoder().fit_transform(df_copy[col])

X = df_copy.drop(["Leakage_Flag","timestamp","leak_no"], axis=1)
y = df_copy["Leakage_Flag"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = Sequential([
    Dense(32, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=20, batch_size=32, verbose=1)

y_pred_prob = model.predict(X_test)
y_pred_ann = (y_pred_prob > 0.5).astype(int)

print("Accuracy :", accuracy_score(y_test, y_pred_ann))
print("Precision:", precision_score(y_test, y_pred_ann, pos_label=1))
print("Recall   :", recall_score(y_test, y_pred_ann, pos_label=1))
print("F1 Score :", f1_score(y_test, y_pred_ann, pos_label=1))

precision_ann = precision_score(y_test, y_pred_ann, pos_label=1)
recall_ann    = recall_score(y_test, y_pred_ann, pos_label=1)
f1_ann        = f1_score(y_test, y_pred_ann, pos_label=1)

"""Graph"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

models = ['LR', 'DT', 'SVM', 'RF', 'XGB', 'LGBM', 'ADABOOST', 'ANN']

precision = [precision_lr, precision_dt, precision_svm,
             precision_rf, precision_xgb, precision_lgbm, precision_adaboost, precision_ann]

recall = [recall_lr, recall_dt, recall_svm,
          recall_rf, recall_xgb, recall_lgbm, recall_adaboost, recall_ann]

f1 = [f1_lr, f1_dt, f1_svm,
      f1_rf, f1_xgb, f1_lgbm, f1_adaboost, f1_ann]

x = np.arange(len(models))
width = 0.2

colors = ['#a6cee3', '#1f78b4', '#08306b']

plt.figure(figsize=(12,6))

plt.bar(x - width, precision, width, label='Precision', color=colors[0])
plt.bar(x, recall, width, label='Recall', color=colors[1])
plt.bar(x + width, f1, width, label='F1 Score', color=colors[2])

plt.xticks(x, models)
plt.ylabel("Score")
plt.xlabel("Models")
plt.title("Model Performance Comparison")
plt.ylim(0,1)

plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

df_table = pd.DataFrame({
    'Model': models,
    'Precision': precision,
    'Recall': recall,
    'F1 Score': f1
})
print(df_table)

"""**Best Model: AdaBoost**"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Create DataFrame (same order as graph)
models = ['LR', 'DT', 'SVM', 'RF', 'XGB', 'LGBM', 'ADA', 'ANN']

precision = [
    precision_lr, precision_dt, precision_svm,
    precision_rf, precision_xgb, precision_lgbm,
    precision_adaboost, precision_ann
]

recall = [
    recall_lr, recall_dt, recall_svm,
    recall_rf, recall_xgb, recall_lgbm,
    recall_adaboost, recall_ann
]

f1 = [
    f1_lr, f1_dt, f1_svm,
    f1_rf, f1_xgb, f1_lgbm,
    f1_adaboost, f1_ann
]

# Create DataFrame
df_heatmap = pd.DataFrame({
    'Model': models,
    'Precision': precision,
    'Recall': recall,
    'F1 Score': f1
})

df_heatmap.set_index('Model', inplace=True)

# Plot heatmap
plt.figure(figsize=(8,5))

sns.heatmap(
    df_heatmap,
    annot=True,           # show values
    cmap='YlGnBu',        # professional color
    fmt=".2f",            # 2 decimal places
    linewidths=0.5
)

plt.title("Model Performance Heatmap")
plt.tight_layout()
plt.show()